### ISSUE TITLE
update to 3.0

### ISSUE THREAD

**Issue by Moulick** [Timac/homebrew-vpnstatus#3]
With the release of https://github.com/Timac/VPNStatus/releases/tag/3.0, Please update the cask and formula. Also consider adding a livecheck block so that creating updating the tap becomes as easy as running `brew bump --open-pr <name>`

**Comment by Timac** [comment]
@Moulick Thanks for the reminder, the cast update has been pushed

**Comment by Timac** [comment]
Regarding the livecheck block, I'm not familiar with brew. If you make a PR, I would happily merge it

**Comment by Moulick** [comment]
@Timac ok I'll try
